# Site settings
title: Perth Linux Users Group
email: committee@plug.org.au
description: >
  PLUG aims to promote Linux and support the users of Linux in Western Australia.
url: "http://plug.org.au" # the base hostname & protocol for your site
twitter_username: plugorgau
github_username:  plugorgau
markdown: kramdown
